# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 1, 1731, 1061))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left = QtWidgets.QGroupBox(self.groupBox_5)
        self.Left.setTitle("")
        self.Left.setObjectName("Left")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Left)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.Left)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Funcitons = QtWidgets.QGroupBox(self.groupBox)
        self.Funcitons.setTitle("")
        self.Funcitons.setObjectName("Funcitons")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Funcitons)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OpenDirBtn = QtWidgets.QPushButton(self.Funcitons)
        self.OpenDirBtn.setObjectName("OpenDirBtn")
        self.verticalLayout.addWidget(self.OpenDirBtn)
        self.NewBoxBtn = QtWidgets.QPushButton(self.Funcitons)
        self.NewBoxBtn.setObjectName("NewBoxBtn")
        self.verticalLayout.addWidget(self.NewBoxBtn)
        self.SaveDirBtn = QtWidgets.QPushButton(self.Funcitons)
        self.SaveDirBtn.setObjectName("SaveDirBtn")
        self.verticalLayout.addWidget(self.SaveDirBtn)
        self.verticalLayout_3.addWidget(self.Funcitons)
        self.Funcitons_2 = QtWidgets.QGroupBox(self.groupBox)
        self.Funcitons_2.setObjectName("Funcitons_2")
        self.formLayout = QtWidgets.QFormLayout(self.Funcitons_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.Funcitons_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.Funcitons_2)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Funcitons_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.line = QtWidgets.QFrame(self.Funcitons_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.line)
        self.label_3 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Funcitons_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.line_2 = QtWidgets.QFrame(self.Funcitons_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.line_2)
        self.label_4 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.Funcitons_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_5 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_2 = QtWidgets.QComboBox(self.Funcitons_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.line_3 = QtWidgets.QFrame(self.Funcitons_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.line_3)
        self.label_6 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_3 = QtWidgets.QComboBox(self.Funcitons_2)
        self.comboBox_3.setEnabled(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_7 = QtWidgets.QLabel(self.Funcitons_2)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_4 = QtWidgets.QComboBox(self.Funcitons_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.Funcitons_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.Funcitons_2)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setMouseTracking(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.pushButton_6)
        self.line_4 = QtWidgets.QFrame(self.Funcitons_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.line_4)
        self.EgoReasonList = QtWidgets.QListView(self.Funcitons_2)
        self.EgoReasonList.setObjectName("EgoReasonList")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.EgoReasonList)
        self.verticalLayout_3.addWidget(self.Funcitons_2)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.horizontalLayout.addWidget(self.Left)
        self.Middle = QtWidgets.QGroupBox(self.groupBox_5)
        self.Middle.setMinimumSize(QtCore.QSize(900, 0))
        self.Middle.setTitle("")
        self.Middle.setObjectName("Middle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Middle)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.Middle)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 868, 932))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Middle)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout.addWidget(self.Middle)
        self.Right = QtWidgets.QGroupBox(self.groupBox_5)
        self.Right.setTitle("")
        self.Right.setObjectName("Right")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Right)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Funcitons_3 = QtWidgets.QGroupBox(self.Right)
        self.Funcitons_3.setObjectName("Funcitons_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.Funcitons_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.Funcitons_3)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Funcitons_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.label_9 = QtWidgets.QLabel(self.Funcitons_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_9 = QtWidgets.QComboBox(self.Funcitons_3)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.label_13 = QtWidgets.QLabel(self.Funcitons_3)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.comboBox_7 = QtWidgets.QComboBox(self.Funcitons_3)
        self.comboBox_7.setEnabled(True)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_14 = QtWidgets.QLabel(self.Funcitons_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.pushButton_7 = QtWidgets.QPushButton(self.Funcitons_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.Funcitons_3)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setMouseTracking(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.pushButton_8)
        self.comboBox_8 = QtWidgets.QComboBox(self.Funcitons_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_15 = QtWidgets.QLabel(self.Funcitons_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.BBoxList = QtWidgets.QListView(self.Funcitons_3)
        self.BBoxList.setObjectName("BBoxList")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.BBoxList)
        self.ObjectReasonList = QtWidgets.QListView(self.Funcitons_3)
        self.ObjectReasonList.setObjectName("ObjectReasonList")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ObjectReasonList)
        self.verticalLayout_5.addWidget(self.Funcitons_3)
        self.ObjectList = QtWidgets.QListView(self.Right)
        self.ObjectList.setObjectName("ObjectList")
        self.verticalLayout_5.addWidget(self.ObjectList)
        self.groupBox_7 = QtWidgets.QGroupBox(self.Right)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_3.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_3.addWidget(self.pushButton_14)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.horizontalLayout.addWidget(self.Right)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindow)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dockWidget)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenDirBtn.setText(_translate("MainWindow", "Open Dir"))
        self.NewBoxBtn.setText(_translate("MainWindow", "Change Save Dir"))
        self.SaveDirBtn.setText(_translate("MainWindow", "Create New RectBox"))
        self.Funcitons_2.setTitle(_translate("MainWindow", "Basic Information"))
        self.label.setText(_translate("MainWindow", "Start Frame"))
        self.label_2.setText(_translate("MainWindow", "End Frame"))
        self.label_3.setText(_translate("MainWindow", "Crash Start Frame"))
        self.label_4.setText(_translate("MainWindow", "Day or Night"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Day"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Night"))
        self.label_5.setText(_translate("MainWindow", "Weather"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Normal"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Rainy"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Snowy"))
        self.label_6.setText(_translate("MainWindow", "If Ego Involved"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "No"))
        self.label_7.setText(_translate("MainWindow", "Ego Car Reason"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "No Fault"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Hard to define"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "None"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Speedy"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Poor Judgement"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Slippery Road"))
        self.pushButton_5.setText(_translate("MainWindow", "Reset"))
        self.pushButton_6.setText(_translate("MainWindow", "Save"))
        self.pushButton_3.setText(_translate("MainWindow", "<< Prev 5"))
        self.pushButton_2.setText(_translate("MainWindow", "< Prev"))
        self.pushButton.setText(_translate("MainWindow", "Next >"))
        self.pushButton_4.setText(_translate("MainWindow", "Next 5 >>"))
        self.Funcitons_3.setTitle(_translate("MainWindow", "Objects Information"))
        self.label_8.setText(_translate("MainWindow", "Object Num"))
        self.label_9.setText(_translate("MainWindow", "Object Type"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Car"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Truck"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "Bike"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Person"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "Animal"))
        self.label_13.setText(_translate("MainWindow", "If Involved"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Yes"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "No"))
        self.label_14.setText(_translate("MainWindow", "Reason"))
        self.pushButton_7.setText(_translate("MainWindow", "Reset"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "No Fault"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "Hard to define"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "None"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Speedy"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "Poor Judgement"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "Slippery Road"))
        self.label_15.setText(_translate("MainWindow", "Bounding Box"))
        self.pushButton_11.setText(_translate("MainWindow", "Delete"))
        self.pushButton_13.setText(_translate("MainWindow", "Edit"))
        self.pushButton_14.setText(_translate("MainWindow", "Save"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):

    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        Ui_MainWindow.__init__(self)
        self.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())
